services:
  frontend:
    image: node:20.12.2-alpine
    container_name: ramen_frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npx next dev -H 0.0.0.0
    environment:
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - INTERNAL_API_URL=http://web:8000/api/v1
      - TZ=Asia/Tokyo
    networks:
      - ramen_net
    depends_on:
      - web

  web:
    build: ./backend
    container_name: ramen_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # - DATABASE_URL=postgresql://ramen_user:ramen_pass@db:5432/ramen_db
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Asia/Tokyo
    networks:
      - ramen_net
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: ramen_postgres
    environment:
      POSTGRES_USER: ramen_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ramen_db
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ramen_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: ramen_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "5050:80"
    networks:
      - ramen_net
    depends_on:
      - db

networks:
  ramen_net:
    driver: bridge

volumes:
  postgres_data: